Ecommerce_project/EcommerceApp/urls.py
from django.urls import path
from .import views
app_name = 'EcommerceApp'
urlpatterns = [
    path('Templates_common', views.Templates_common),
    path('', views.Index, name="Index"),
    path('Register', views.Register, name="Register"),
    path('Login', views.Login, name="Login"),
    path('product_details/<slug:slug>/', views.Product_details_view.as_view(), name="product_details"),
    path('add_cart/<pk>', views.add_to_cart, name="add_cart"),
    path('cart_view', views.cart_view, name="cart_view"),
    path('remove_item_from_cart/<pk>', views.remove_item_from_cart, name="remove_item_from_cart"),
    path('incresae_cart/<pk>', views.incresae_cart, name="incresae_cart"),
    path('decrease_cart/<pk>', views.decrease_cart, name="decrease_cart"),
    path('athur_reg', views.athur_reg, name="athur_reg"),
]

Ecommerce_project/Ecommerce_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('EcommerceApp.urls')),
]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

Ecommerce_project/templates/shopping-cart.html
{%extends 'Templates_common.html'%}
{% block title%}
 {% endblock%}


 {% block contant%}

 {% load static %}

            <!-- Begin Li's Breadcrumb Area -->
            <div class="breadcrumb-area">
                <div class="container">
                    <div class="breadcrumb-content">
                        <ul>
                            <li><a href="index.html">Home</a></li>
                            <li class="active">Shopping Cart</li>
                        </ul>
                    </div>
                </div>
            </div>
            <!-- Li's Breadcrumb Area End Here -->
            <!--Shopping Cart Area Strat-->
            <div class="Shopping-cart-area pt-60 pb-60">
                <div class="container">
                    <div class="row">
                        <div class="col-12">
                            <form action="#">
                                <div class="table-content table-responsive">
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th class="li-product-remove">remove</th>
                                                <th class="li-product-thumbnail">images</th>
                                                <th class="cart-product-name">Product</th>
                                                <th class="li-product-price">Unit Price</th>
                                                <th class="li-product-quantity">Quantity</th>
                                                <th class="li-product-subtotal">Total</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        {% for cart in carts %}
                                            <tr>
                                                <td class="li-product-remove"><a href="{% url 'EcommerceApp:remove_item_from_cart' pk=cart.pk %}"><i class="fa fa-times"></i></a></td>
                                                <td class="li-product-thumbnail"><a href="#"><img src="{{cart.item.image.url}}" alt="Li's Product Image"></a></td>
                                                <td class="li-product-name"><a href="#">{{cart.item.product_name}}</a></td>
                                                <td class="li-product-price"><span class="amount">{{cart.item.new_price}}</span></td>
                                                <td class="quantity">
                                                    <label>Quantity</label>
                                                    <div class="cart-plus-minus">
                                                        <input class="cart-plus-minus-box" value="{{cart.quantity }}" type="text">
                                                         <div  ><a href="{% url 'EcommerceApp:incresae_cart' pk=cart.item.pk %}"><i class="fa fa-angle-down"></i></a></div>
                                                            <a href="{% url 'EcommerceApp:decrease_cart' pk=cart.item.pk %}" ><i class="fa fa-angle-up"></i></a>
                                                    </div>
                                                </td>
                                                <td class="product-subtotal"><span class="amount">{{cart.get_total}}</span></td>
                                            </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                                <div class="row">
                                    <div class="col-12">
                                        <div class="coupon-all">
                                            <div class="coupon">
                                                <input id="coupon_code" class="input-text" name="coupon_code" value="" placeholder="Coupon code" type="text">
                                                <input class="button" name="apply_coupon" value="Apply coupon" type="submit">
                                            </div>
                                            <div class="coupon2">
                                                <input class="button" name="update_cart" value="Update cart" type="submit">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-5 ml-auto">
                                        <div class="cart-page-total">
                                            <h2>Cart totals</h2>
                                            <ul>
                                                <li>Subtotal <span>{{order.get_totals}}</span></li>
                                                <li>Total <span>{{order.get_totals}}</span></li>
                                            </ul>
                                            <a href="#">Proceed to checkout</a>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <!--Shopping Cart Area End-->
{% endblock%}